FROM node:21-alpine as builder

WORKDIR /app

# Install dependencies
COPY yarn.lock package.json ./
RUN yarn

# RUN yarn global add serve

# Copy source code
COPY . .

# # Build the app
# RUN yarn build
EXPOSE 3000

CMD ["yarn","dev","--host","0.0.0.0"]
